GTravel/Areas/Admin/Controllers/AttractionController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using GTravel.Domain;
using GTravel.Domain.Data;
using GTravel.Domain.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace GTravel.Areas.Admin.Controllers
{
    public class AttractionController : AdminController
    {
        public AttractionController(ApplicationDbContext db)
            :base(db)
        {

        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? id, int? cityId)
        {
            SelectListViewModel<Attraction> vmAttraction = new SelectListViewModel<Attraction>()
            {
                Entity = new Attraction(),
                SelectListItems = new SelectList(_db.Cities.OrderBy(c => c.Name), "Id", "Name")
            };

            if (cityId != null)
            {
                var dbCity = _db.Cities.Find(cityId);
                if (dbCity != null)
                {
                    vmAttraction.Entity.CityId = dbCity.Id;
                }
            }

            if (id != null)
            {
                vmAttraction.Entity = _db.Attractions.FirstOrDefault(a => a.Id == id);
            }

            return View(vmAttraction);
        }


        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Upsert(int? id, [Bind("Name,Description,CityId")] Attraction attraction)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    attraction.Name = ConvertToCamelCase(attraction.Name);

                    _db.Attractions.Add(attraction);
                }
                else
                {
                    var dbAttraction = _db.Attractions.FirstOrDefault(a => a.Id == id);

                    dbAttraction.CityId = attraction.CityId;
                    dbAttraction.Description = attraction.Description;
                    dbAttraction.Name = ConvertToCamelCase(attraction.Name);

                    _db.Attractions.Update(dbAttraction);
                }
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));

            }

            return View(attraction);

        }




        #region API CALLS

        public IActionResult GetAll()
        {
            return Json(new { data = _db.Attractions
                .Include(a=>a.City)
                .Select(a=> new { 
                a.Id,a.Name, City = a.City.Name, a.City.State
                })
                .ToList() });
        
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var dbAttraction = _db.Attractions.FirstOrDefault(a => a.Id == id);
            if (dbAttraction == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            _db.Attractions.Remove(dbAttraction);
            _db.SaveChanges();
            return Json(new { success = true, message = "Delete Successful" });

        }

        #endregion
        public string ConvertToCamelCase(string input)
        {
            TextInfo myTI = new CultureInfo("en-US", false).TextInfo;
            return myTI.ToTitleCase(input);
        }
    }
}

GTravel/Areas/Admin/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using GTravel.Domain;
using GTravel.Domain.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GTravel.Areas.Admin.Controllers
{
    public class CityController :AdminController
    {

        public CityController(ApplicationDbContext db)
            :base(db)
        {

        }
        public IActionResult Index()
        {
            return View();
        }


        public IActionResult Upsert(int? id)
        {
            var city = new City();
            if (id != null)
            {
                city = _db.Cities.FirstOrDefault(c => c.Id == id);
            }


            return View(city);
        }


        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Upsert(int? id, [Bind("Name,State,PostCode,Longitude,Latitude")]City city)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    city.Name = ConvertToCamelCase(city.Name);
                    city.State = Enum.GetName(typeof(SD.States), int.Parse(city.State));
                    _db.Cities.Add(city);
                }
                else {
                    var dbCity = _db.Cities.FirstOrDefault(c => c.Id == id);
                                        
                    dbCity.State = Enum.GetName(typeof(SD.States),int.Parse(city.State));
                    dbCity.PostCode = city.PostCode;
                    dbCity.Latitude = city.Latitude;
                    dbCity.Longitude = city.Longitude;
                    dbCity.Name = ConvertToCamelCase(city.Name);
                    
                   
                    _db.Cities.Update(dbCity);              
                
                }
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(city);

        }

        #region API CALLS

        public IActionResult GetAll()
        {
             
            return Json(new { data = _db.Cities.ToList() });    
        
        
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var dbCity = _db.Cities.FirstOrDefault(a => a.Id == id);
            if (dbCity == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            _db.Cities.Remove(dbCity);
            _db.SaveChanges();
            return Json(new { success = true, message = "Delete Successful" });

        }
        #endregion

        public string ConvertToCamelCase(string input)
        {
            TextInfo myTI = new CultureInfo("en-US", false).TextInfo;
            return myTI.ToTitleCase(input);
        }

       
    }
}

GTravel/Areas/Admin/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using GTravel.Domain;
using GTravel.Domain.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GTravel.Areas.Admin.Controllers
{
    [Authorize(Roles =SD.Admin)]
    public class EmployeeController : AdminController
    {
        public EmployeeController(ApplicationDbContext db)
            :base(db)
        {

        }
        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claims = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var allButCurrentEmployees = _db.Employees.Where(u => u.Id != claims.Value).ToList();

            return View(allButCurrentEmployees);
        }
    }
}

GTravel/Areas/Admin/Controllers/TourController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using GTravel.Domain;
using GTravel.Domain.Data;
using GTravel.Domain.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace GTravel.Areas.Admin.Controllers
{
    public class TourController : AdminController
    {
        private readonly IWebHostEnvironment _hostEnvironment;

        public TourController(ApplicationDbContext db, IWebHostEnvironment hostEnvironment)
            :base(db)
        {
            _hostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {

            return View();
        }


        public IActionResult Create()
        {
            SelectListViewModel<Tour> tourVm = new SelectListViewModel<Tour>()
            {
                Entity = new Tour(),
                SelectListItems = new SelectList(_db.Cities.OrderBy(c => c.Name).ToList(), "Name", "Name")
            };

            return View(tourVm);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Create([Bind("Name, TourDurationDays,DepartureLocation,BriefDescription,FullDescription,AccommodationNumberOfNights,MaxCapacity,RRP")] Tour tour)
        {
            if (ModelState.IsValid)
            {              
                tour.ImageUrl = GetImageUrl();
                tour.StatusId = 1;
                _db.Tours.Add(tour);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            else {

                SelectListViewModel<Tour> tourVmForRedirect = new SelectListViewModel<Tour>()
                {
                    Entity = new Tour(),
                    SelectListItems = new SelectList(_db.Cities.OrderBy(c => c.Name).ToList(), "Name", "Name")
                };

                return View(tourVmForRedirect);
            }        
        }

        public IActionResult Update(int id)
        {
            if (id == 0)
            { 
                return RedirectToAction(nameof(Index));
            }
            var dbTour = _db.Tours.FirstOrDefault(t => t.Id == id);

            SelectListViewModel<Tour> tourVm = new SelectListViewModel<Tour>()
            {
                Entity = dbTour,
                SelectListItems = new SelectList(_db.Cities.OrderBy(c => c.Name).ToList(), "Name", "Name")
            };

            return View(tourVm);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Update(int id,[Bind("Name, TourDurationDays,DepartureLocation,BriefDescription,FullDescription,AccommodationNumberOfNights,MaxCapacity,RRP")] Tour tour)
        {
            if (ModelState.IsValid)
            {
                var dbTour = _db.Tours.Find(id);
                if (dbTour == null)
                {
                    return NotFound();
                }
                else {
                    dbTour.Name = tour.Name;
                    dbTour.TourDurationDays = tour.TourDurationDays;
                    dbTour.DepartureLocation = tour.DepartureLocation;
                    dbTour.BriefDescription = tour.BriefDescription;
                    dbTour.FullDescription = tour.FullDescription;
                    dbTour.AccommodationNumberOfNights = tour.AccommodationNumberOfNights;
                    dbTour.MaxCapacity = tour.MaxCapacity;
                    dbTour.RRP = tour.RRP;
                    dbTour.ImageUrl = GetImageUrl(dbTour.ImageUrl);

                    _db.Tours.Update(dbTour);
                    _db.SaveChanges();
                    return RedirectToAction(nameof(Index));

                }
            }
            else {
                var dbTour = _db.Tours.FirstOrDefault(t => t.Id == id);

                SelectListViewModel<Tour> tourVmForRedirect = new SelectListViewModel<Tour>()
                {
                    Entity = dbTour,
                    SelectListItems = new SelectList(_db.Cities.OrderBy(c => c.Name).ToList(), "Name", "Name")
                };


                return View(tourVmForRedirect);
            }
        }


        public IActionResult Details(int id)
        {
            var dbTour = _db.Tours
                .Include(t=>t.Meal)
                .Include(t=>t.TourCities)
                    .ThenInclude(tc=>tc.City)
                .Include(t => t.TourCities)
                    .ThenInclude(tc=>tc.TourAttractions)
                        .ThenInclude(tca=>tca.Attraction)
                .FirstOrDefault(t => t.Id == id);
           
            return View(dbTour);
        }




        #region API CALLS

        public IActionResult GetAll()
        {
            
            return Json(new
            {
                data = _db.Tours
                .Include(t => t.TourCities)
                .Select(t => new {
                    t.Id, t.Name,t.MaxCapacity,t.Status
                })
                .ToList()
            });


        }


        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var dbTour = _db.Tours.FirstOrDefault(p => p.Id == id);
            string webRootPath = _hostEnvironment.WebRootPath;
            DeleteImageUrl(webRootPath, dbTour.ImageUrl);
            
            if (dbTour == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            _db.Tours.Remove(dbTour);
            _db.SaveChanges();
            return Json(new { success = true, message = "Delete Successful" });

        }

        [HttpPost]
        public IActionResult Publish(int id)
        {
            var dbTour = _db.Tours.FirstOrDefault(p => p.Id == id);
            if (dbTour == null)
            {
                return Json(new { success = false, message = "Error while publishing, please try again" });
            }

            dbTour.StatusId = 2;
            _db.Tours.Update(dbTour);
            _db.SaveChanges();

            return Json(new { success = true, message = "Publish Successful!" });

        }

        #endregion

        public string GetImageUrl(string imageUrl = "")
        {
            string webRootPath = _hostEnvironment.WebRootPath;
            var files = HttpContext.Request.Form.Files;

            if (files.Count == 0 && imageUrl != "")
            {
                return imageUrl;

            }            
            string fileName = Guid.NewGuid().ToString();
            var uploads = Path.Combine(webRootPath, @"images");
            var extension = Path.GetExtension(files[0].FileName);
            DeleteImageUrl(webRootPath, imageUrl);
            

            using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
            {
                files[0].CopyTo(fileStreams);
            }
            string updatedImageUrl = @"\images\" + fileName + extension;


            return updatedImageUrl;
        }

        public void DeleteImageUrl(string webRootPath,string imageUrl)
        {
            imageUrl = Path.Combine(webRootPath, imageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(imageUrl))
            {
                System.IO.File.Delete(imageUrl);
            }

        }
    }
}

GTravel/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-outline-primary form-control">Create</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

GTravel/Views/Shared/_EditAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-outline-primary form-control" asp-route-id="@Model">Edit</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

GTravel/Views/Shared/_Layout.cshtml
@using GTravel.Domain
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GTravel</title>
    <link rel="icon" href="~/Images/gtravel_logo.png" type="image/x-icon">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
</head>
<body>
    <header>
                @{
                    var area = "Customer";
                    var backgroundFill = "bg-transparent";
                    if (User.IsInRole(SD.Admin) || User.IsInRole(SD.Manager)) { area = "Admin"; backgroundFill = "bg-primary"; }
                }
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm  navbar-light @backgroundFill box-shadow">
            <div class="container ">
                <a class="navbar-brand p-0" asp-area="@area" asp-controller="Home" asp-action="Index">
                    <img src="~/Images/gtravel_logo.png" width="90" height="70" class="d-inline-block align-top " alt="logo" />

                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse ">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1 ">

                        @if (User.IsInRole(SD.Admin) || User.IsInRole(SD.Manager))
                        {
                            <li class="nav-item text-light">
                                <a class="nav-link home text-light" asp-area="Admin" asp-controller="Tour" asp-action="Index">Tours</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link home text-light" asp-area="Admin" asp-controller="Attraction" asp-action="Index">Attractions</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link home text-light" asp-area="Admin" asp-controller="City" asp-action="Index">Cities</a>
                            </li>

                            @if (User.IsInRole(SD.Admin))
                            {
                                <li class="nav-item">
                                    <a class="nav-link home text-light" asp-area="Admin" asp-controller="Employee" asp-action="Index">Employees</a>
                                </li>

                            }
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link home" asp-area="Customer" asp-controller="Home" asp-action="Index">All Tours</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropDown" role="button" data-toggle="dropdown"
                                   aria-haspopup="true" aria-expanded="false">
                                    Tours By State
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropDown">
                                    <a class="dropdown-item" asp-route-state="NSW" asp-controller="Home" asp-action="StateDetails">New South Wales</a>
                                    <a class="dropdown-item" asp-route-state="QLD" asp-controller="Home" asp-action="StateDetails">Queensland</a>
                                    <a class="dropdown-item" asp-route-state="WA" asp-controller="Home" asp-action="StateDetails">Western Australia</a>
                                    <a class="dropdown-item" asp-route-state="SA" asp-controller="Home" asp-action="StateDetails">South Australia</a>
                                    <a class="dropdown-item" asp-route-state="VIC" asp-controller="Home" asp-action="StateDetails">Victoria</a>
                                    <a class="dropdown-item" asp-route-state="TAS" asp-controller="Home" asp-action="StateDetails">Tasmania</a>
                                    <a class="dropdown-item" asp-route-state="NT" asp-controller="Home" asp-action="StateDetails">Northern Territory</a>
                                    <a class="dropdown-item" asp-route-state="ACT" asp-controller="Home" asp-action="StateDetails">Australian Capital Territory</a>

                                </div>
                            </li>
                            
                        }
                    </ul>
                </div>
            </div>
        </nav>
        @if (area == "Customer")
        {
            <div class="jumbotron jumbotron-fluid" style="text-align:center;">

            </div>
        }
    </header>
    <br />
    <div class="container my-3 pb-5 bg-white border shadow">
        <main role="main" class="pb-5 pl-3 ">

            @RenderBody()
        </main>
        <span class="row col-12 " style="height:150px;"></span>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="row col-12 justify-content-center pt-3">
                <a class="btn-floating btn-lg btn-fb" role="button"><i class="fab fa-facebook-f"></i></a>
                <a class="btn-floating btn-lg btn-ins" role="button"><i class="fab fa-instagram"></i></a>
                <a class="btn-floating btn-lg btn-tw" role="button"><i class="fab fa-twitter"></i></a>
            </div>
            <div class="row col-12  justify-content-center">&copy; 2020 - GTravel - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></div>

        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/2.9.0/jquery.serializejson.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>



    @RenderSection("Scripts", required: false)
</body>
</html>