GTravel/Areas/Admin/Controllers/MealController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GTravel.Domain;
using GTravel.Domain.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GTravel.Areas.Admin.Controllers
{
    public class MealController : AdminController
    {
        public MealController(ApplicationDbContext db)
            :base(db)
        {

        }

        public IActionResult Details(int id)
        {
            var dbTour = _db.Tours.Include(t => t.Meal).FirstOrDefault(t => t.Id == id);
                       
            return View(dbTour);

        }

        public IActionResult Upsert(int tourId)
        {
            var dbtour = _db.Tours.Include(t => t.Meal).FirstOrDefault(t => t.Id == tourId);
            if (dbtour.Meal != null)
            {
                return View(dbtour.Meal);
            }
            else {
                Meal meal = new Meal();
                meal.TourId = tourId;
                
            return View(meal);
            }       
        
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Upsert(int tourId, [Bind("Breakfast,Lunch,Dinner")] Meal meal)
        {
            if (ModelState.IsValid)
            {
                var dbTour = _db.Tours.Include(t => t.Meal).FirstOrDefault(t => t.Id == tourId);

                if (dbTour.Meal == null)
                {
                    meal.TourId = tourId;
                    _db.Meals.Add(meal);

                }
                else
                {

                    var dbMeal = dbTour.Meal;
                    dbMeal.Breakfast = meal.Breakfast;
                    dbMeal.Lunch = meal.Lunch;
                    dbMeal.Dinner = meal.Dinner;
                    _db.Meals.Update(dbMeal);
                }

                _db.SaveChanges();
                return RedirectToAction("Details", new { id = tourId });

            }
            else {

                return RedirectToAction("Index","Tour");
            
            }
        
        }


        #region API CALLS

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var dbMeal = _db.Meals.FirstOrDefault(a => a.Id == id);
            if (dbMeal == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            _db.Meals.Remove(dbMeal);
            _db.SaveChanges();
            return Json(new { success = true, message = "Delete Successful" });
        }

        #endregion
    }
}

GTravel/Areas/Admin/Views/Meal/Details.cshtml
@model GTravel.Domain.Tour

@{
    var title = "Meal Details: " + Model.Name;
    var meal = Model.Meal;
    var createOrUpdate = "Update";
}


<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-transparent">
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Tour">Tours</a></li>
        <li class="breadcrumb-item active" aria-current="page">Meal Details</li>
    </ol>
</nav>

<div class="backgroundWhite container mt-4">
    <div class=" row col-12 ">
        @if (Model.Meal != null)
        {
            <div>
                <h4>@title</h4>

            </div>
            <div class="row col-12">
                <dl class="row col-8 my-4">
                    @if (meal.Breakfast != 0)
                    {
                        <dt class="col-sm-4">Breakfast: </dt>
                        <dd class="col-sm-5">@meal.Breakfast</dd>
                    }
                    @if (meal.Lunch != 0)
                    {
                        <dt class="col-sm-4">Lunch: </dt>
                        <dd class="col-sm-5">@meal.Lunch</dd>
                    }
                    @if (meal.Dinner != 0)
                    {

                        <dt class="col-sm-4">Dinner: </dt>
                        <dd class="col-sm-5">@meal.Dinner</dd>
                    }
                </dl>

            </div>
        }
        else
        {
            createOrUpdate = "Create";
            <div class="row col-12 d-flex justify-content-center" style="height:200px">

                <h4>There are currently no meals planned for this tour</h4>
            </div>

        }

    </div>

    <div class=" row">
        <div class="col-8 ">
            <div class="row">
                <div class="col">
                    <a asp-action="Upsert" asp-controller="Meal" class="btn btn-outline-primary form-control" asp-route-tourId="@Model.Id">@createOrUpdate</a>
                </div>
                <div class="col">
                    <a asp-action="Index" asp-controller="Tour" class="btn btn-success form-control">Back to List</a>
                </div>
                @if (Model.Meal != null)
                {
                    <div class="col-1">
                        <a onclick=Delete("/Admin/meal/Delete/@meal.Id") class='btn btn-danger text-white' style='cursor:pointer; width:50px;'>
                            <i class='far fa-trash-alt'></i>
                        </a>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="~/js/mealDetails.js"></script>


}

GTravel/Areas/Admin/Views/Meal/Upsert.cshtml
@model GTravel.Domain.Meal
@{
    var title = "Create Meals";
}


@if (Model.Id != 0)
{
    title = "Update Meals";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-transparent">
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Tour">Tours</a></li>
        <li class="breadcrumb-item"><a asp-action="Details" asp-controller="Meal" asp-route-id="@Model.TourId">Meal Details</a></li>
        <li class="breadcrumb-item active" aria-current="page">@title</li>
    </ol>
</nav>
<form method="post" asp-action="Upsert">
    <div class="row px-2 mx-2 backgroundWhite border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="col-12">
            <h2 class="text-primary mt-3 mb-4">@title</h2>
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="@Model.Breakfast"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="@Model.Breakfast" class="form-control" />
                        <span asp-validation-for="@Model.Breakfast" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="@Model.Lunch"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="@Model.Lunch" class="form-control" />
                        <span asp-validation-for="@Model.Lunch" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="@Model.Dinner"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="@Model.Dinner" class="form-control" />
                        <span asp-validation-for="@Model.Dinner" class="text-danger"></span>
                    </div>
                </div>


                <div class="form-group row">
                    <div class="col-8 offset-4">
                        @if (Model.Id != 0)
                        {
                            <div class="row">
                                <div class="col">
                                    <button type="submit" class="btn btn-outline-primary form-control" asp-route-tourId="@Model.TourId">Update</button>
                                </div>
                                <div class="col">
                                    <a asp-action="Details" asp-route-id="@Model.TourId" class="btn btn-success form-control">Back to List</a>
                                </div>
                            </div>
                        }
                        else
                        {
                            <div class="row">
                                <div class="col">
                                    <button type="submit" class="btn btn-outline-primary form-control" asp-route-tourId="@Model.TourId">Create</button>
                                </div>
                                <div class="col">
                                    <a asp-action="Details" asp-route-id="@Model.TourId" class="btn btn-success form-control">Back to List</a>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

</form>